### ISSUE TITLE
decord._ffi.base.DECORDError: [16:33:15] /github/workspace/src/video/video_reader.cc:486: Error: av_read_frame failed with 1094995529

### ISSUE THREAD

**Issue by pp-jia** [OpenBMB/MiniCPM-V#507]
在进行推理时，控制台decord包报错，请问如何解决？
<img width="960" alt="d6be595e69b01e33237d42a7d04e16c" src="https://github.com/user-attachments/assets/e52170a4-19c8-47b2-8b21-844c83d3563e">

**Comment by iceflame89** [comment]
Please provide the original video file for reproduce.  
May be the video is broken, you can try another video.

**Comment by pp-jia** [comment]
> Please provide the original video file for reproduce. May be the video is broken, you can try another video.

Thanks for your response, it is indeed the video that is corrupted, I have fixed the corrupted video using the following command.
ffmpeg -fflags +discardcorrupt -i "$filepath" -c copy "$output_file"
